# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=64, unique=True)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['text'], name='todo_todo_text_317bfe_idx'),
        ),
    ]
